#############################################################################
#
# Project Makefile
#
# (c) Wouter van Ooijen (www.voti.nl) 2016
#
# This file is in the public domain.
# 
#############################################################################

# source files in this project (main.cpp is automatically assumed)
SOURCES := rectangle.cpp circle.cpp line.cpp picture.cpp

# header files in this project
HEADERS := shape.hpp rectangle.hpp exceptions.hpp circle.hpp line.hpp picture.hpp 
# other places to look for files for this project
SEARCH  := 

# set REATIVE to the next higher directory 
# and defer to the Makefile.due there
RELATIVE := $(RELATIVE)../
include $(RELATIVE)Makefile.native
