#############################################################################
#
# Project Makefile
#
# (c) Wouter van Ooijen (www.voti.nl) 2016
#
# This file is in the public domain.
# 
#############################################################################

# Sources and Headers sfml
SOURCES := game_model.cpp interface_controller_sfml.cpp sfml_interface.cpp
HEADERS := game_model.hpp move.hpp interface_controller_sfml.hpp sfml_interface.hpp


# Sources and Headers text
# SOURCES := game_model.cpp interface_controller_text.cpp text_interface.cpp
# HEADERS := game_model.hpp move.hpp interface_controller_text.hpp text_interface.hpp

# other places to look for files for this project
SEARCH  := 

# set REATIVE to the next higher directory 
# and defer to the Makefile.due there
RELATIVE := $(RELATIVE)../
include $(RELATIVE)Makefile.native
